# Generated by Django 3.0.3 on 2020-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='file_obj',
            field=models.FileField(upload_to='z`', verbose_name='Файл документа'),
        ),
    ]
