# Generated by Django 3.0.3 on 2020-03-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docslist', '0002_auto_20200224_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='executed',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='failures',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='work_contract',
        ),
        migrations.AlterField(
            model_name='docs',
            name='file_obj',
            field=models.FileField(upload_to='', verbose_name='Файл документа'),
        ),
    ]
